export const SOCKET_LIMITS = {
  MAX_SOCKETS_PER_USER: Number(process.env.SOCKET_MAX_CONNECTIONS || 5),
  CONNECTION_SWEEP_MS: Number(process.env.SOCKET_CONNECTION_SWEEP_MS || 5 * 60 * 1000),
  MESSAGE_RATE_LIMIT: Number(process.env.SOCKET_MESSAGE_LIMIT || 12),
  MESSAGE_RATE_WINDOW_MS: Number(process.env.SOCKET_MESSAGE_WINDOW_MS || 10 * 1000),
  REACTION_RATE_LIMIT: Number(process.env.SOCKET_REACTION_LIMIT || 20),
  REACTION_RATE_WINDOW_MS: Number(process.env.SOCKET_REACTION_WINDOW_MS || 10 * 1000),
  TYPING_RATE_LIMIT: Number(process.env.SOCKET_TYPING_LIMIT || 40),
  TYPING_RATE_WINDOW_MS: Number(process.env.SOCKET_TYPING_WINDOW_MS || 10 * 1000),
  TYPING_INDICATOR_TIMEOUT_MS: Number(process.env.SOCKET_TYPING_INDICATOR_MS || 1200),
  PRESENCE_DEBOUNCE_MS: Number(process.env.SOCKET_PRESENCE_DEBOUNCE_MS || 250),
};

export const ACTIVE_PRESENCE_KEY_PREFIX = 'presence:active:';
